### ISSUE TITLE
Dependency breaks - "code.google.com/p/gcfg"

### ISSUE THREAD

**Issue by newsera** [42wim/cssh#1]
Dependency breaks - "code.google.com/p/gcfg"

Google migrated to "gopkg.in/gcfg.v1"

Can you help update the code accordingly? 

C:\cssh>go install github.com/42wim/cssh
src\github.com\42wim\cssh\config.go:8:2: cannot find package "code.google.com/p/gcfg" in any of:
        C:\Go\src\code.google.com\p\gcfg (from $GOROOT)

C:\cssh\cssh-master>go get github.com/42wim/cssh
package code.google.com/p/gcfg: unrecognized import path "code.google.com/p/gcfg" (parse https://code.google.com/p/gcfg?go-get=1: no go-import meta tags)

Cannot run as well

C:\cssh\cssh-master\cssh>go run cssh.go
# command-line-arguments

.\cssh.go:21: undefined: config
.\cssh.go:36: undefined: readConfig
.\cssh.go:41: undefined: getCredentials

**Comment by 42wim** [comment]
Hi, thanks for the rapport.
Fixed this and pushed some local changes too and released v0.2 :-)
