### ISSUE TITLE
Unable to SSH

### ISSUE THREAD

**Issue by newsera** [42wim/cssh#2]
Thanks for taking a look at the other issue and fixing it. 

But seems like its SSH this time. Does it have anything to do with "github.com/ScriptRock/crypto/ssh" being deprecated? 

I am using Password based authentication here and updated credentials on cssh.conf

n@u:~/cssh/cssh-0.2$ ./cssh-linux64 -cmd "show ip int br" -host r1
2016/08/24 10:41:03 ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain

C:\cssh\cssh-master>cssh64.exe -cmd "show ip int br" -host r1
2016/08/24 10:36:41 ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain

Am I missing something?

**Comment by 42wim** [comment]
That's strange. I've tested it before the release. 
- What device are you trying to connect to ?
- Could you paste me your complete cssh.conf ? Do change the password, but if possible nothing else
- Could you do a normal `ssh -v r1` and paste the lines containing `remote software version` 

Should look like this

```
debug1: Remote protocol version 2.0, remote software version Cisco-1.25
```

(github.com/ScriptRock/crypto/ssh is not being deprecated btw)

**Comment by 42wim** [comment]
@newsera any update ?
